version: 1.0.0
title: Chris' Page
tagline: "random stuff i did"
description: "this is a place for me to write about random stuff i did"
url: https://shadow578.github.io
baseurl: ""
paginate: 5
permalink: pretty

author:
  name: Chris / shadow578
  url: https://shadow578.github.io/

github:
  repo: "https://github.com/shadow578/shadow578.github.io"

plugins:
  - jekyll-paginate
  - jekyll-relative-links

relative_links:
  enabled: true

